blank_issues_enabled: true
contact_links:
    - name: e927f58393bb319d27d334dd12258b2521fb4889
      url: https://github.com/zkSync-Community-Hub/zksync-developers/discussions
      about: Please provide feedback, and ask questions here.