blank_issues_enabled: true
contact_links:
    - name: e15e33a07c0920189fc336391f538c3dad53da73
      url: https://github.com/zkSync-Community-Hub/zksync-developers/discussions
      about: Please provide feedback, and ask questions here.